---
title: "conftree"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{conftree}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library("conftree")
set.seed(123)
```

# Regression

## Data: bike sharing usage in Washington, D.C.

```{r}
data(bikes, package = "conftree")
```

## Select learner

```{r, message=FALSE}
library("tidymodels")
forest <- rand_forest() %>%
  set_mode("regression") %>%
  set_engine("ranger")
```

## Detect subgroups

```{r}
groups <- r2p(
  data = bikes,
  target = "count",
  learner = forest,
  cv_folds = 1,
  alpha = 0.1,
  gamma = 0.01,
  lambda = 0.5,
  max_groups = 4
)
```

## Understand results

```{r}
groups
```
```{r}
summary(groups)
```

```{r}
plot(groups)
```

# Treatment Effects

## Data: simulate synthetic data

```{r, include = FALSE}
library(remotes)
install_github("susanne-207/htesim")
```

```{r}
library(htesim)
set.seed(1234)
dgp <- dgp(p = pF_exp_x1_x2,
           m = mF_x1,
           t = tF_div_x1_x2,
           model = "normal",
           xmodel = "unif",
           sd = 1)
sim <- simulate(object = dgp,
                nsim = 500L,
                d = 4L)
```

## Select learner

```{r}
linear <- linear_reg() %>%
  set_mode("regression") %>%
  set_engine("lm")
```

## Detect subgroups

```{r}
groups_hte <- r2p_hte(
  data = sim,
  target = "y",
  learner = linear,
  cv_folds = 500,
  alpha = 0.1,
  gamma = 0.01,
  lambda = 0.5,
  max_groups = 8,
  treatment = "trt"
)
```

## Understand results

```{r}
plot(groups_hte)
```
